SCREEN_WIDTH = 1200 #640
SCREEN_HEIGHT = 800 #640

OVERWORLD_TILE_SIZE = 16


UNDERWORLD_TILE_SIZE = 32
UNDERWORLD_DRAW_DISTANCE = 8.1 # 8.1 default, 40 good for debugging
DARKNESS_DEBUG = False
DEBUG_DRAW_HITBOXES = False

KNOCKBACK_SPEED = 5